GestionBox/GestionBox/Controllers/ClasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionBox.Models;
using GestionBox.Models.ViewModel;
using GestionBox.Services;
using Microsoft.AspNetCore.Authorization;

namespace GestionBox.Controllers
{
    //[Authorize(Roles = "Administrador")] // con esto restringimos el controlador entero. :)
    public class ClasesController : Controller
    {
        private readonly IClase _ClaseServices;
        private readonly IHorario _HorarioServices;
        

        public ClasesController(IClase ClasesServices, IHorario HorarioServices)
        {
            _ClaseServices = ClasesServices;
            _HorarioServices = HorarioServices;

        }

        // GET: Clases
        public async Task<IActionResult> Index(string name, string tipo, DateTime dia)
        {
 
            List<Clase> clase = await _ClaseServices.GetClaseAsync();

            HorarioClaseVM hcvm = new HorarioClaseVM()
            {
                Horarios = await _HorarioServices.GetHorarioAsync(),
                Clases = await _ClaseServices.GetClaseAsync()
            };

            if (String.IsNullOrEmpty(name) && String.IsNullOrEmpty(tipo) && dia.ToString("dd/MM/yyyy") == "01/01/0001")
            {
                return View(hcvm);
            }
            if (!String.IsNullOrEmpty(name))
            {
                hcvm.Clases = hcvm.Clases.Where(x => x.Nombre.ToLower().Contains(name.ToLower())).ToList();
            }
            if (!String.IsNullOrEmpty(tipo))
            {
                hcvm.Clases = hcvm.Clases.Where(x => x.Tipo == tipo).ToList();
            }
            if (dia.ToString("dd/MM/yyyy") != "01/01/0001")
            {
                
                hcvm.Horarios = hcvm.Horarios.Where(x => x.Dia.ToString() == dia.ToString()).ToList();
                hcvm.Clases = hcvm.Horarios.Select(x => x.Clase).Distinct().ToList();
            }
            return View(hcvm);
        }

        // GET: Clases/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clase = await _ClaseServices.GetClaseByIdAsync(id);
                
            if (clase == null)
            {
                return NotFound();
            }

            return View(clase);
        }

        // GET: Clases/Create
        [Authorize(Roles="Administrador")]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Administrador")]
        // POST: Clases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,Tipo,Imagen")] Clase clase)
        {
            if (ModelState.IsValid)
            {
                await _ClaseServices.CreateClaseAsync(clase);
                
                return RedirectToAction(nameof(Index));
            }
            return View(clase);
        }

        // GET: Clases/Edit/5

        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clase = await _ClaseServices.GetClaseByIdAsync(id);
            if (clase == null)
            {
                return NotFound();
            }
            return View(clase);
        }

        [Authorize(Roles = "Administrador")]
        // POST: Clases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion,Tipo,Imagen")] Clase clase)
        {
            if (id != clase.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _ClaseServices.UpdateClaseAsync(clase);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_ClaseServices.ClaseExist(clase.Id)) // como lo metemos aquí, podemos borrar el Método ClaseExist del final. 
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clase);
        }

        // GET: Clases/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clase = await _ClaseServices.GetClaseByIdAsync(id);
                
            if (clase == null)
            {
                return NotFound();
            }

            return View(clase);
        }

        [Authorize(Roles = "Administrador")]
        // POST: Clases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clase = await _ClaseServices.GetClaseByIdAsync(id);
            await _ClaseServices.DeleteClaseAsync(clase);
            
            return RedirectToAction(nameof(Index));
        }
        

    }
}

GestionBox/GestionBox/Controllers/HorariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionBox.Data;
using GestionBox.Models;
using GestionBox.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace GestionBox.Controllers
{
    
    public class HorariosController : Controller
    {
        private readonly IHorario _HorarioServices;
        private readonly UserManager<BoxUser> _boxUser;


        public HorariosController(IHorario horarioServices, UserManager<BoxUser> boxUser)
        {
            _HorarioServices = horarioServices;
            _boxUser = boxUser;


        }

        [Authorize(Roles = "Administrador")]
        // GET: Horarios
        public async Task<IActionResult> Index(int dia, int mes)
        {
            List<Horario> horario = await _HorarioServices.GetHorarioAsync();


            if (dia == 0 && mes == 0)
            {
                return View(horario);
            }
            
            if (dia != 0)
            {
                horario = horario.Where(x => x.Dia.Day == dia).ToList();
            }
            if (mes != 0)
            {
                horario = horario.Where(x => x.Dia.Month == mes).ToList();
            }


            return View(horario);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Horarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horario = await _HorarioServices.GetHorarioByIdAsync(id);

            if (horario == null)
            {
                return NotFound();
            }

            return View(horario);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Horarios/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Administrador")]
        // POST: Horarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Horario horario)
        {
            if (ModelState.IsValid)
            {
                await _HorarioServices.CreateHorarioAsync(horario);

                return RedirectToAction(nameof(Index));
            }
            return View(horario);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Horarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horario = await _HorarioServices.GetHorarioByIdAsync(id);

            if (horario == null)
            {
                return NotFound();
            }
            return View(horario);
        }

        [Authorize(Roles = "Administrador")]
        // POST: Horarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Horario horario)
        {
            if (id != horario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _HorarioServices.UpdateHorarioAsync(horario);

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_HorarioServices.HorarioExist(horario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(horario);
        }

        [Authorize(Roles = "Administrador")]
        // GET: Horarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var horario = await _HorarioServices.GetHorarioByIdAsync(id);

            if (horario == null)
            {
                return NotFound();
            }

            return View(horario);
        }

        [Authorize(Roles = "Administrador")]
        // POST: Horarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var horario = await _HorarioServices.GetHorarioByIdAsync(id);
            await _HorarioServices.DeleteHorarioAsync(horario);

            return RedirectToAction(nameof(Index));
        }

        //private bool HorarioExists(int id)
        //{
        //    return _HorarioServices.Horarios.Any(e => e.Id == id);
        //}

        public async Task<IActionResult> Reservar(int id)
        {

            Horario horario = await _HorarioServices.GetHorarioByIdAsync(id);

            return View(horario);
        }
    }
}

GestionBox/GestionBox/Views/Clases/Create.cshtml
@model GestionBox.Models.Clase


@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>




<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" id="BotonCrearClase" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la Lista Clases</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionBox/GestionBox/Views/Clases/Delete.cshtml
@model GestionBox.Models.Clase

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h3>Seguro que quieres borrar esto?</h3>
<div>
    
    <dl class="row">
        <dt class = "col-sm-2">
            Nombre:
        </dt>
        <dd class = "col-sm-10">
            @Model.Nombre
        </dd>
        <dt class = "col-sm-2">
            Descripcion:
        </dt>
        <dd class="col-sm-10">
            @Model.Descripcion
        </dd>
        <dt class = "col-sm-2">
            Tipo:
        </dt>
        <dd class="col-sm-10">
            @Model.Tipo
        </dd>
        <dt class = "col-sm-2">
            Imagen:
        </dt>
        <dd class="ImagenMisclases col-sm-10">
            <img src="@Model.Imagen" alt="@Model.Nombre" />
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la Lista Clases</a>
    </form>
</div>

GestionBox/GestionBox/Views/Clases/Details.cshtml
@model GestionBox.Models.Clase

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>

    <dl class="row">
        <dt class="col-sm-2">
            Id Clase:
        </dt>
        <dd class="col-sm-10">
            @Model.Id
        </dd>
        <dt class="col-sm-2">
            Nombre:
        </dt>
        <dd class="col-sm-10">
            @Model.Nombre
        </dd>
        <dt class="col-sm-2">
            Descripcion:
        </dt>
        <dd class="col-sm-10">
            @Model.Descripcion
        </dd>
        <dt class="col-sm-2">
            Tipo:
        </dt>
        <dd class="col-sm-10">
            @Model.Tipo
        </dd>
        <dt class="col-sm-2">
            Imagen:
        </dt>
        <dd class="ImagenMisclases col-sm-10">
            <img src="@Model.Imagen" alt="@Model.Nombre" />
        </dd>
    </dl>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
        <a asp-action="Index">Volver a la Lista Clases</a>
    </div>
</div>

GestionBox/GestionBox/Views/Clases/Edit.cshtml
@model GestionBox.Models.Clase

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="ImagenMisclases form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la Lista Clases</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionBox/GestionBox/Views/Clases/Index.cshtml
@model GestionBox.Models.ViewModel.HorarioClaseVM

@using Microsoft.AspNetCore.Identity
@inject UserManager<BoxUser> _userManager
@inject SignInManager<BoxUser> _signInManager

@{
    ViewData["Title"] = "Index";
}

<h1>Clases</h1>

@{BoxUser user = await _userManager.GetUserAsync(User);}

<h1>Tarifa: @user.Tarifa </h1>

@if (_signInManager.IsSignedIn(User))
{


    @if (await _userManager.IsInRoleAsync(user, "Administrador")) // si es admin puede verlo.
    {
        <p>
            <a asp-action="Create">Crear Nueva Clase</a>
        </p>
    }

}

<div class="buscador row">
    <form asp-controller="Clases" asp-action="Index">
        <input type="text" placeholder="Introduce el nombre de la clase" name="name" />

        <select class="selectMisclases" name="tipo">
            <option value="">Tipo </option>

            @{List<string> tipoClase = Model.Clases.Select(x => x.Tipo).Distinct().ToList(); }


            @foreach (string tipo in tipoClase)
            {
                <option class="option" value="@tipo">@tipo</option>
            }

        </select>

        <select class="selectMisclases" name="dia">
            <option value="">Dia </option>

            @{List<DateTime> diasClase = Model.Horarios.Select(x => x.Dia).Distinct().ToList(); }

            @foreach (DateTime dia in diasClase)
            {
                <option class="option" value="@dia">@dia.Day</option>
            }

        </select>
        <input type="submit" value="Buscar" />

    </form>
</div>

<div class="row ClasesView">
    @foreach (Clase clase in Model.Clases)
    {
        <div class="card col-lg-4 col-md-6 col-sm-12">
            <div>
                <img class="card-img-top" src="@clase.Imagen" alt="@clase.Nombre">
            </div>

            <div class="card-body">
                <h5 class="card-title">@clase.Nombre</h5>
                <p class="card-text">@clase.Descripcion</p>
                <p class="card-text">@clase.Tipo</p>
                <p>
                    <a class="btn btn-primary" data-toggle="collapse" href="#CollapseExample-@clase.Id" role="button" aria-expanded="false" aria-controls="CollapseExample">
                        Desplegar Horarios
                    </a>

                </p>
                <div>
                    @if (_signInManager.IsSignedIn(User))
                    {

                        @if (await _userManager.IsInRoleAsync(user, "Administrador")) // si es admin puede verlo.
                        {

                            <div>
                                <a asp-action="Edit" asp-route-id="@clase.Id">Editar</a> |
                                <a asp-action="Details" asp-route-id="@clase.Id">Detalles</a> |
                                <a asp-action="Delete" asp-route-id="@clase.Id">Borrar</a>

                            </div>

                        }

                    }

                </div>
                <div class="row">
                    <div class="collapse" id="CollapseExample-@clase.Id">
                        @foreach (Horario horario in clase.Horarios)
                        {
                            <div class="row">
                                <p>@horario.Hora &nbsp;</p>

                                <form asp-route-id="@horario.Id" asp-controller="Horarios" asp-action="Reservar">

                                    <!--asp-route-id le pasa por parametros el Id al metodo Reservar-->
                                    <input class="btn btn-primary" type="submit" value="Reservar" />

                                </form>
                            </div>

                        }

                    </div>
                </div>



            </div>
        </div>
    }

</div>