VideoClub/VideoClub/Models/UserFilm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VideoClub.Models
{
    public class UserFilm
    {
        public int Id { get; set; }
        public DateTime Daterental { get; set; }
        public DateTime? Returndate { get; set; } //? asi admite valores nulos
        
        public int UserId { get; set; }
        public int FilmId { get; set; }
        public Film Film { get; set; }
        public User User { get; set; }


    }
}

VideoClub/VideoClub/Controllers/UserFilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VideoClub.Models;

namespace VideoClub.Controllers
{
    public class UserFilmsController : Controller
    {
        private readonly VideoClubContext _context;

        public UserFilmsController(VideoClubContext context)
        {
            _context = context;
        }

        // GET: UserFilms
        public async Task<IActionResult> Index(string pendiente)
        {
            List<UserFilm> alquileres = await _context.UserFilm.Include(u => u.Film)
                .Include(u => u.User)
                .Where(x => x.UserId == 1).ToListAsync();

            if (String.IsNullOrEmpty(pendiente))
            {
                return View(alquileres);
            }

            if (pendiente == "si")
            {
                alquileres = alquileres.Where(x => x.Returndate == null).ToList();
            }
            else
            {
                alquileres = alquileres.Where(x => x.Returndate != null).ToList();
            }

            return View(alquileres);
            
        }

        // GET: UserFilms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFilm = await _context.UserFilm
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userFilm == null)
            {
                return NotFound();
            }

            return View(userFilm);
        }

      
        // GET: UserFilms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserFilms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Daterental,Returndate")] UserFilm userFilm)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userFilm);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userFilm);
        }

        // GET: UserFilms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFilm = await _context.UserFilm.FindAsync(id);
            if (userFilm == null)
            {
                return NotFound();
            }
            return View(userFilm);
        }

        // POST: UserFilms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Daterental,Returndate")] UserFilm userFilm)
        {
            if (id != userFilm.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userFilm);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserFilmExists(userFilm.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userFilm);
        }

        // GET: UserFilms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userFilm = await _context.UserFilm
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userFilm == null)
            {
                return NotFound();
            }

            return View(userFilm);
        }

        // POST: UserFilms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userFilm = await _context.UserFilm.FindAsync(id);
            _context.UserFilm.Remove(userFilm);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserFilmExists(int id)
        {
            return _context.UserFilm.Any(e => e.Id == id);
        }

        public async Task<IActionResult> ConfirmarAlquiler(int id)
        {
            Film film = await _context.Film.FindAsync(id); //localiza el film por id
            User user = await _context.User.FindAsync(1);

            UserFilm alquiler = new UserFilm
            {
                Film = film, // no hace falta filmid ni userid, al tener el user y el film los coge. 
                User = user,
                Daterental = DateTime.Now,
            };

            _context.Add(alquiler); // añadir objeto a tabla UserFilm
            film.Rented = "Si"; // cambiamos estado pelicula
            _context.Update(film); // actualizamos tabla film
            await _context.SaveChangesAsync(); // guardar cambios BBDD

            return RedirectToAction("index"); // redirige al metodo Index del controller. 
            //RedirectToAction(nameof(Index)); // lo mismo que el anterior 
            //RedirectToAction("Index","Films"); // Redirige al Index de otro controlador. UTIL. 
        }
        public async Task<IActionResult> DevolverPelicula(int id)
        {
            UserFilm alquiler = await _context.UserFilm.Include(x => x.Film).FirstOrDefaultAsync(x => x.Id == id); //Include para los datos d ela peli, y aqui no deja usar Find asi que usamos FirstOrDefault que es lo mismo. 
            return View(alquiler);
        }
        public async Task<IActionResult> ConfirmarDevolucion(int id)
        {
            UserFilm alquiler = await _context.UserFilm.Include(x => x.Film).FirstOrDefaultAsync(x => x.Id == id);
            alquiler.Returndate = DateTime.Now; // Le damos una fecha de devolucion
            Film film = alquiler.Film;
            film.Rented = "No"; // cambiamos estado pelicula
            _context.Update(alquiler);
            _context.Update(film);
            await _context.SaveChangesAsync();

            return RedirectToAction("index", "Films");
        }
    }
}

VideoClub/VideoClub/Views/UserFilms/Create.cshtml
@model VideoClub.Models.UserFilm

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UserFilm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Daterental" class="control-label"></label>
                <input asp-for="Daterental" class="form-control" />
                <span asp-validation-for="Daterental" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Returndate" class="control-label"></label>
                <input asp-for="Returndate" class="form-control" />
                <span asp-validation-for="Returndate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VideoClub/VideoClub/Views/UserFilms/Delete.cshtml
@model VideoClub.Models.UserFilm

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserFilm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Daterental)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Daterental)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Returndate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Returndate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

VideoClub/VideoClub/Views/UserFilms/Details.cshtml
@model VideoClub.Models.UserFilm

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UserFilm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Daterental)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Daterental)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Returndate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Returndate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

VideoClub/VideoClub/Views/UserFilms/DevolverPelicula.cshtml
@model VideoClub.Models.UserFilm

@{
    ViewData["Title"] = "DevolverPelicula";
}



<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Pelicula Alquilada
        </dt>
        <dd class = "col-sm-10">
            @Model.Film.Title
        </dd>
        <dt class = "col-sm-2">
            Fecha Alquiler
        </dt>
        <dd class = "col-sm-10">
            @Model.Daterental
        </dd>
        <dt class = "col-sm-2">
            Imagen
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Film.Image"/>
        </dd>
       
    </dl>
</div>
<div>
    <a asp-action="ConfirmarDevolucion" asp-route-id="@Model.Id">Confirmar Devolucion</a> |
    <a asp-action="Index">Back to List</a>
</div>

VideoClub/VideoClub/Views/UserFilms/Edit.cshtml
@model VideoClub.Models.UserFilm

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserFilm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Daterental" class="control-label"></label>
                <input asp-for="Daterental" class="form-control" />
                <span asp-validation-for="Daterental" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Returndate" class="control-label"></label>
                <input asp-for="Returndate" class="form-control" />
                <span asp-validation-for="Returndate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VideoClub/VideoClub/Views/UserFilms/Index.cshtml
@model List<VideoClub.Models.UserFilm>

@{
    ViewData["Title"] = "Index";
}
<form asp-controller="UserFilms" asp-action="Index">
    <select name="pendiente">
        <option value="">Todos</option>
        <option value="si">Pendientes</option>
        <option value="no">Finalizados</option>
    </select>
    <input type="submit" value="Buscar" />
</form>



@if (Model.Count == 0)
{
    <h1>No tienes ningún alquiler</h1>
}
else
{
    @*<p>
            <a asp-action="Create">Create New</a>
        </p>*@

    <table class="table">
        <thead>
            <tr>
                <th>
                    Fecha alquiler
                </th>
                <th>
                    Fecha Devolución
                </th>
                <th>
                    Película
                </th>
                <th>
                    Imagen
                </th>
                <th>
                    Devolver Película
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (UserFilm alquiler in Model)
            {

                if (@alquiler.Daterental.AddDays(2) < DateTime.Now && @alquiler.Returndate == null)
                {

                    <tr class="table-danger">
                        <td>
                            @alquiler.Daterental
                        </td>
                        <td>
                            @alquiler.Returndate
                        </td>
                        <td>
                            @alquiler.Film.Title
                        </td>
                        <td>
                            <img src="@alquiler.Film.Image" />
                        </td>
                        <td>
                            <a asp-controller="UserFilms" asp-action="DevolverPelicula" asp-route-id="@alquiler.Id">Devolver Pelicula</a>
                        </td>
                    </tr>

                }

                else
                {

                    <tr>
                        <td>
                            @alquiler.Daterental
                        </td>
                        <td>
                            @alquiler.Returndate
                        </td>
                        <td>
                            @alquiler.Film.Title
                        </td>
                        <td>
                            <img src="@alquiler.Film.Image" />
                        </td>

                    </tr>

                }

                @*<td>
                        <a asp-action="Edit" asp-route-id="@alquiler.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@alquiler.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@alquiler.Id">Delete</a>
                    </td>*@

            }
        </tbody>
    </table>

}